;; This is an operating system configuration generated by the graphical
;; installer and then refined for the guixpc EXWM machine.

(use-modules (gnu)
             (guix gexp)
             (nonguix transformations)
             (sk packages terminals))
(use-service-modules cups desktop networking ssh sound xorg)

(define %guixpc-monitor-config
  "
Section \"Monitor\"
  Identifier \"HDMI-A-0\"
  Modeline \"3440x1440_100\" 534.60 3440 3488 3520 3600 1440 1443 1448 1485 +HSync +VSync
  Option \"PreferredMode\" \"3440x1440_100\"
EndSection")

((nonguix-transformation-guix)
 ((nonguix-transformation-linux)
  (operating-system
    (locale "en_US.utf8")
    (timezone "America/New_York")
    (keyboard-layout
     (keyboard-layout "us"
                      #:options '("caps:escape")))

    (host-name "guixpc")

    (kernel-arguments
     (cons* "modprobe.blacklist=pcspkr"
            "video=HDMI-A-0:3440x1440@100"
            %default-kernel-arguments))

    (users
     (cons* (user-account
              (name "skydive420dz")
              (comment "Rafael Oliveira")
              (group "users")
              (home-directory "/home/skydive420dz")
              (shell (file-append (specification->package "fish")
                                  "/bin/fish"))
              (supplementary-groups '("wheel" "netdev" "audio" "video")))
            %base-user-accounts))

    (packages
     (append
      ;; Keep this order stable: Guix profile collisions are resolved by order.
      (list kitty-latest)
      (map specification->package
           '("curl"
             "fastfetch-minimal"
             "btop"
             "emacs"
             "emacs-exwm"
             "emacs-desktop-environment"
             "xset"
             "fzf"
             "git"
             "bluez"
             "blueman"
             "bzmenu"
             "pipemixer"
             "pamixer"
             "fish"
             "ranger"
             "ungoogled-chromium"
             "xdg-utils"
             "file"
             "bat"
             "chafa"
             "mediainfo"
             "ffmpegthumbnailer"
             "poppler"
             "atool"
             "unzip"
             "odt2txt"
             "jq"
             "emacs-rainbow-delimiters"
             "emacs-visual-fill-column"
             "emacs-lsp-mode"
             "emacs-company"
             "emacs-flycheck"
             "emacs-lsp-ui"
             "emacs-lsp-ivy"
             "emacs-vterm"
             "emacs-lsp-treemacs"
             "emacs-yasnippet"
             "emacs-geiser"
             "emacs-geiser-guile"
             "emacs-sly"
             "emacs-lua-mode"
             "emacs-json-mode"
             "emacs-org"
             "emacs-org-bullets"
             "emacs-evil"
             "emacs-projectile"
             "emacs-counsel-projectile"
             "emacs-evil-collection"
             "emacs-magit"
             "emacs-helpful"
             "emacs-general"
             "emacs-use-package"
             "emacs-which-key"
             "emacs-ivy-rich"
             "emacs-counsel"
             "emacs-diminish"
             "emacs-ivy"
             "emacs-doom-modeline"
             "ncurses"
             "ripgrep"
             "vim"
             "font-iosevka-term"
             "font-nerd-symbols"
             "font-google-noto-emoji"
             "font-nerd-jetbrains-mono"
             "emacs-all-the-icons"
             "emacs-all-the-icons-dired"
             "sbcl"
             "lua"
             "lua-language-server"
             "python"
             "python-lsp-server"
             "ruff"
             "shellcheck"
             "shfmt"
             "clang"
             "gcc-toolchain"
             "make"
             "gdb"
             "pkg-config"
             "emacs-all-the-icons-ibuffer"
             "xwallpaper"
             "picom"
             "xrandr"))

      %base-packages))

    (services
     (modify-services
      (append
       (list
        (service openssh-service-type)
        (service bluetooth-service-type)
        (service xorg-server-service-type
                 (xorg-configuration
                  (keyboard-layout keyboard-layout)
                  (extra-config (list %guixpc-monitor-config))))
        (service startx-command-service-type
                 (xorg-configuration
                  (keyboard-layout keyboard-layout)
                  (extra-config (list %guixpc-monitor-config)))))
       %desktop-services)

      (delete gdm-service-type)
      (delete pulseaudio-service-type)

      (mingetty-service-type
       config => (if (string=? (mingetty-configuration-tty config) "tty1")
                     (mingetty-configuration
                      (inherit config)
                      (auto-login "skydive420dz")
                      (clear-on-logout? #t)
                      (print-issue #f)
                      (print-hostname #f))
                     config))

      (guix-service-type
       config => (guix-configuration
                  (inherit config)
                  (extra-options '("--cores=4"
                                   "--max-jobs=1"))))

      (elogind-service-type
       config => (elogind-configuration
                  (inherit config)
                  (idle-action 'ignore)
                  (handle-lid-switch 'ignore)
                  (handle-lid-switch-external-power 'ignore)
                  (handle-suspend-key 'ignore)))))

    (bootloader
     (bootloader-configuration
      (bootloader grub-efi-bootloader)
      (targets (list "/boot/efi"))
      (theme (grub-theme
              (resolution '(3440 . 1440))
              (gfxmode '("3440x1440" "2560x1440" "1920x1080" "auto"))))
      (keyboard-layout keyboard-layout)))

    (swap-devices
     (list (swap-space
            (target (uuid "2083a12f-123c-4893-8b64-1358fe666180")))))

    (file-systems
     (cons* (file-system
              (mount-point "/boot/efi")
              (device (uuid "F476-0B09" 'fat16))
              (type "vfat"))
            (file-system
              (mount-point "/")
              (device (uuid "e4279482-6b04-4f8b-8dab-3f70ae3daa65" 'ext4))
              (type "ext4"))
            (file-system
              (mount-point "/home")
              (device (uuid "70807a48-75ba-4fa2-a760-64e930805665" 'ext4))
              (type "ext4"))
            %base-file-systems)))))
