;; This is an operating system configuration generated by the graphical
;; installer and then refined for the guixpc EXWM machine.

(use-modules (gnu)
             (gnu packages freedesktop)
             (guix gexp)
             (guix git-download)
             (guix packages)
             (nonguix transformations)
             (sk packages terminals))
(use-service-modules cups dbus desktop networking ssh sound xorg)

(load (string-append (dirname (current-filename))
                     "/../package-ownership.scm"))

;; Elogind 255.17 can leave completed SSH sessions leaderless and stuck in
;; "closing".  255.24 contains the upstream session-GC fixes for FIFO EOF,
;; leader exit, and release timeout handling.
(define elogind-255.24
  (package
    (inherit elogind)
    (version "255.24")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/elogind/elogind")
             (commit (string-append "v" version))))
       (file-name (git-file-name (package-name elogind) version))
       (sha256
        (base32 "0id4gjwjxcb860ibpr5irc3birgr89m650q4alrkpqdnd81nfyvk"))))))

(define %guixpc-monitor-config
  "
Section \"Monitor\"
  Identifier \"HDMI-A-0\"
  Modeline \"3440x1440_100\" 534.60 3440 3488 3520 3600 1440 1443 1448 1485 +HSync +VSync
  Option \"PreferredMode\" \"3440x1440_100\"
EndSection")

((nonguix-transformation-guix)
 ((nonguix-transformation-linux)
  (operating-system
    (locale "en_US.utf8")
    (timezone "America/New_York")
    (keyboard-layout
     (keyboard-layout "us"
                      #:options '("caps:escape")))

    (host-name "guixpc")

    (kernel-arguments
     (cons* "modprobe.blacklist=pcspkr"
            "video=HDMI-A-0:3440x1440@100"
            %default-kernel-arguments))

    (users
     (cons* (user-account
              (name "skydive420dz")
              (comment "Rafael Oliveira")
              (group "users")
              (home-directory "/home/skydive420dz")
              (shell (file-append (specification->package "fish")
                                  "/bin/fish"))
              (supplementary-groups '("wheel" "netdev" "audio" "video")))
            %base-user-accounts))

    (packages
     (append
      ;; Kitty stays in the System recovery floor because EXWM's terminal
      ;; launcher requires it.  Home owns normal applications and tooling.
      (list kitty-latest)
      (map specification->package %guixpc-recovery-package-specifications)

      %base-packages))

    (services
     (modify-services
      (append
       (list
        (service openssh-service-type)
        ;; Keep the controller available before a paired speaker powers on.
        ;; Guix defaults this to false, so the adapter can still be off during
        ;; the Bose's startup reconnect attempt.
        (service bluetooth-service-type
                 (bluetooth-configuration
                  (auto-enable? #t)))
        ;; Give PipeWire bounded realtime scheduling through the standard
        ;; system D-Bus/Polkit service instead of broad CAP_SYS_NICE grants.
        (service rtkit-service-type)
        (service xorg-server-service-type
                 (xorg-configuration
                  (keyboard-layout keyboard-layout)
                  (extra-config (list %guixpc-monitor-config))))
        (service startx-command-service-type
                 (xorg-configuration
                  (keyboard-layout keyboard-layout)
                  (extra-config (list %guixpc-monitor-config)))))
       %desktop-services)

      (delete gdm-service-type)
      (delete pulseaudio-service-type)

      (mingetty-service-type
       config => (if (string=? (mingetty-configuration-tty config) "tty1")
                     (mingetty-configuration
                      (inherit config)
                      (auto-login "skydive420dz")
                      (clear-on-logout? #t)
                      (print-issue #f)
                      (print-hostname #f))
                     config))

      (guix-service-type
       config => (guix-configuration
                  (inherit config)
                  (extra-options '("--cores=4"
                                   "--max-jobs=1"))))

      (elogind-service-type
       config => (elogind-configuration
                  (inherit config)
                  (elogind elogind-255.24)
                  (idle-action 'ignore)
                  (handle-lid-switch 'ignore)
                  (handle-lid-switch-external-power 'ignore)
                  (handle-suspend-key 'ignore)))))

    (bootloader
     (bootloader-configuration
      (bootloader grub-efi-bootloader)
      (targets (list "/boot/efi"))
      (theme (grub-theme
              (resolution '(3440 . 1440))
              (gfxmode '("3440x1440" "2560x1440" "1920x1080" "auto"))))
      (keyboard-layout keyboard-layout)))

    (swap-devices
     (list (swap-space
            (target (uuid "2083a12f-123c-4893-8b64-1358fe666180")))))

    (file-systems
     (cons* (file-system
              (mount-point "/boot/efi")
              (device (uuid "F476-0B09" 'fat16))
              (type "vfat"))
            (file-system
              (mount-point "/")
              (device (uuid "e4279482-6b04-4f8b-8dab-3f70ae3daa65" 'ext4))
              (type "ext4"))
            (file-system
              (mount-point "/home")
              (device (uuid "70807a48-75ba-4fa2-a760-64e930805665" 'ext4))
              (type "ext4"))
            %base-file-systems)))))
