;;; sk-keys.el --- Global and leader keys -*- lexical-binding: t; -*-

(global-set-key (kbd "C-c e") #'sk/window-open-eshell)
(global-set-key (kbd "C-c t") #'sk/window-open-term)

(use-package general
  :config
  (general-create-definer rune/leader-keys
    :keymaps '(normal insert visual emacs)
    :prefix "SPC"
    :global-prefix "C-SPC")

  (rune/leader-keys
    "."  '(sk/window-counsel-fzf :which-key "fuzzy file")
    ","  '(counsel-switch-buffer :which-key "switch buffer")

    "b"  '(:ignore t :which-key "buffers")
    "bb" '(counsel-ibuffer :which-key "buffer prompt")
    "bi" '(sk/window-open-ibuffer :which-key "ibuffer panel")
    "bk" '(sk/kill-current-buffer :which-key "kill")
    "bK" '(sk/kill-ordinary-buffers-and-dashboard :which-key "kill all")

    "f"  '(:ignore t :which-key "files")
    "fC" '(sk/copy-current-file :which-key "copy current")
    "fD" '(sk/delete-current-file :which-key "delete current")
    "fR" '(sk/rename-current-file :which-key "rename current")
    "ff" '(sk/window-counsel-find-file :which-key "find")
    "fr" '(recentf-open-files :which-key "recent")
    "fs" '(save-buffer :which-key "save")
    "fu" '(sk/sudo-find-file :which-key "sudo find")
    "fU" '(sk/sudo-current-file :which-key "sudo current")
    "fy" '(sk/yank-current-file-path :which-key "copy path")
    "fY" '(sk/yank-current-file-path-relative :which-key "copy relative")

    "p"  '(:ignore t :which-key "projects")
    "pp" '(projectile-switch-project :which-key "switch")
    "pf" '(sk/window-counsel-projectile-find-file :which-key "find file")
    "ps" '(projectile-ripgrep :which-key "ripgrep")
    "pc" '(projectile-compile-project :which-key "compile")

    "g"  '(:ignore t :which-key "git")
    "gg" '(magit-status :which-key "status")

    "s"  '(:ignore t :which-key "search")
    "ss" '(counsel-rg :which-key "ripgrep")
    "sg" '(counsel-git :which-key "git files")
    "sp" '(counsel-projectile-rg :which-key "project")

    "c"  '(:ignore t :which-key "code")
    "ca" '(sk/code-action :which-key "action")
    "cc" '(compile :which-key "compile")
    "cC" '(recompile :which-key "recompile")
    "cd" '(sk/code-definition :which-key "definition")
    "cD" '(sk/code-references :which-key "references")
    "cf" '(sk/format-buffer :which-key "format")
    "ci" '(sk/code-implementation :which-key "implementation")
    "cj" '(sk/code-type-definition :which-key "jump type")
    "ck" '(sk/code-docs :which-key "docs")
    "cl" '(lsp :which-key "start lsp")
    "cr" '(sk/code-rename :which-key "rename")
    "cs" '(lsp-ivy-workspace-symbol :which-key "symbols")
    "ct" '(sk/code-symbols :which-key "symbol tree")
    "cW" '(delete-trailing-whitespace :which-key "trim whitespace")
    "cx" '(sk/code-diagnostics :which-key "diagnostics")

    "h"  '(:ignore t :which-key "help")
    "h." '(helpful-at-point :which-key "at point")
    "hf" '(helpful-callable :which-key "function")
    "hv" '(helpful-variable :which-key "variable")
    "hk" '(helpful-key :which-key "key")

    "l"  '(:ignore t :which-key "lisp")
    "lb" '(sk/lisp-eval-buffer :which-key "eval buffer")
    "ld" '(sk/lisp-eval-defun :which-key "eval defun")
    "le" '(sk/lisp-eval-last-sexp :which-key "eval sexp")
    "lk" '(sk/lisp-docs :which-key "docs")
    "lr" '(sk/lisp-repl :which-key "repl")
    "l[" '(puni-slurp-backward :which-key "slurp backward")
    "l]" '(puni-slurp-forward :which-key "slurp forward")
    "l{" '(puni-barf-backward :which-key "barf backward")
    "l}" '(puni-barf-forward :which-key "barf forward")
    "l(" '(puni-wrap-round :which-key "wrap round")
    "lu" '(puni-splice :which-key "unwrap")
    "lR" '(puni-raise :which-key "raise")
    "lt" '(puni-transpose :which-key "transpose")

    "w"  '(:ignore t :which-key "windows")
    "w=" '(balance-windows :which-key "balance")
    "wf" '(sk/window-toggle-full-frame :which-key "full frame")
    "wh" '(sk/window-left :which-key "left")
    "wj" '(sk/window-down :which-key "down")
    "wk" '(sk/window-up :which-key "up")
    "wl" '(sk/window-right :which-key "right")
    "wo" '(delete-other-windows :which-key "only")
    "wr" '(winner-redo :which-key "redo layout")
    "ws" '(sk/window-split-below-and-focus :which-key "split below")
    "wu" '(winner-undo :which-key "undo layout")
    "wv" '(sk/window-split-right-and-focus :which-key "split right")
    "ww" '(sk/window-next :which-key "next")
    "wW" '(sk/window-previous :which-key "previous")
    "wx" '(delete-window :which-key "close")
    "wH" '(sk/window-resize-left :which-key "resize left")
    "wJ" '(sk/window-resize-down :which-key "resize down")
    "wK" '(sk/window-resize-up :which-key "resize up")
    "wL" '(sk/window-resize-right :which-key "resize right")

    "o"  '(:ignore t :which-key "open")
    "od" '(sk/window-open-dired :which-key "dired")
    "oe" '(sk/window-open-eshell :which-key "eshell")
    "ot" '(sk/window-open-treemacs :which-key "treemacs")
    "ov" '(sk/window-open-vterm :which-key "vterm")

    "t"  '(:ignore t :which-key "toggles")
    "tt" '(counsel-load-theme :which-key "choose theme")

    "q"  '(:ignore t :which-key "quit")
    "qq" '(save-buffers-kill-terminal :which-key "quit")
    "qa" '(save-buffers-kill-emacs :which-key "quit emacs")
    "qw" '(sk/save-buffer-and-quit :which-key "save quit")
    "qf" '(kill-emacs :which-key "force quit")
    "qr" '(sk/reload-config :which-key "reload config")))

(provide 'sk-keys)

;;; sk-keys.el ends here
