# Generated by (sk theme); do not edit.
# schema=2 palette=GNU Emacs 30.2 etc/themes/modus-vivendi-tinted-theme.el
# Generated Fish syntax, pager, and prompt color adapter.
set -g -- fish_color_normal 'ffffff'
set -g -- fish_color_command '6ae4b9'
set -g -- fish_color_keyword '2fafff' '--bold'
set -g -- fish_color_quote 'fec43f'
set -g -- fish_color_redirection '2fafff' '--bold'
set -g -- fish_color_end '6ae4b9'
set -g -- fish_color_error 'ff5f59'
set -g -- fish_color_param 'ffffff'
set -g -- fish_color_valid_path 'ffffff' '--underline'
set -g -- fish_color_option '2fafff'
set -g -- fish_color_comment 'c6daff' '--italics'
set -g -- fish_color_selection 'ffffff' '--background=555a66' '--bold'
set -g -- fish_color_operator '2fafff'
set -g -- fish_color_escape 'fec43f'
set -g -- fish_color_autosuggestion '989898'
set -g -- fish_color_cancel 'ff5f59' '--reverse'
set -g -- fish_color_search_match 'ffffff' '--background=555a66' '--bold'
set -g -- fish_color_history_current 'ffffff' '--background=555a66' '--bold'
set -g -- fish_color_host 'c6daff'
set -g -- fish_color_host_remote 'fec43f'
set -g -- fish_color_status 'ff5f59'
set -g -- fish_color_cwd '6ae4b9'
set -g -- fish_color_cwd_root 'ff5f59'
set -g -- fish_color_user '6ae4b9'
set -g -- fish_color_background '--background=0d0e1c'
set -g -- fish_color_statement_terminator '2fafff'
set -g -- fish_pager_color_progress '0d0e1c' '--background=2fafff' '--bold'
set -g -- fish_pager_color_background '--background=1d2235'
set -g -- fish_pager_color_prefix '2fafff' '--bold' '--underline'
set -g -- fish_pager_color_completion 'ffffff'
set -g -- fish_pager_color_description 'c6daff' '--italics'
set -g -- fish_pager_color_secondary_background '--background=4a4f69'
set -g -- fish_pager_color_secondary_prefix '2fafff' '--bold'
set -g -- fish_pager_color_secondary_completion 'ffffff'
set -g -- fish_pager_color_secondary_description 'c6daff' '--italics'
set -g -- fish_pager_color_selected_background '--background=555a66'
set -g -- fish_pager_color_selected_prefix 'ffffff' '--background=555a66' '--bold'
set -g -- fish_pager_color_selected_completion 'ffffff' '--background=555a66'
set -g -- fish_pager_color_selected_description 'ffffff' '--background=555a66' '--italics'
set -g -- __sk_theme_prompt_path 'ffffff'
set -g -- __sk_theme_prompt_path_background '--background=4a4f69'
set -g -- __sk_theme_prompt_git_branch '2fafff'
set -g -- __sk_theme_prompt_git_status 'c6daff'
set -g -- __sk_theme_prompt_success '6ae4b9'
set -g -- __sk_theme_prompt_error 'ff5f59'

function fish_prompt
    set -l last_status $status
    set -l branch (__sk_git_branch)
    set -l git_status (__sk_git_status)

    set_color normal
    set_color $__sk_theme_prompt_path_background $__sk_theme_prompt_path
    echo -n ' '(__sk_prompt_pwd)' '
    set_color normal

    if test -n "$branch"
        echo -n ' '
        set_color $__sk_theme_prompt_git_branch
        echo -n '󰊢 '$branch' '
        set_color $__sk_theme_prompt_git_status
        echo -n $git_status' '
        set_color normal
    end

    echo

    if test $last_status -eq 0
        set_color $__sk_theme_prompt_success
    else
        set_color $__sk_theme_prompt_error
    end
    echo -n '❯ '
    set_color normal
end

function fish_right_prompt
end
