# Generated by (sk theme); do not edit.
# schema=2 palette=GNU Emacs 30.2 etc/themes/modus-vivendi-tinted-theme.el
# Same-shell data only: starts no process and emits no toolkit scale override.
SK_THEME_LOGICAL_DPI='96'
SK_THEME_INTEGER_SCALE='1'
SK_THEME_SCALE_OWNERSHIP='inherit-verified'
SK_THEME_WALLPAPER='assets/wallpapers/waifu-cyberpunk.png'
SK_THEME_WALLPAPER_FIT='zoom'
SK_THEME_PICOM_EMACS_OPACITY_PERCENT='85'
SK_THEME_PICOM_CONFIG='/dev/null'
SK_THEME_PICOM_BACKEND='glx'
SK_THEME_PICOM_VSYNC='true'
XCURSOR_THEME='Bibata-Modern-Ice'
XCURSOR_SIZE='32'
export XCURSOR_THEME XCURSOR_SIZE
