# guixpc opener policy

mime ^text, label editor = ${VISUAL:-$EDITOR} -- "$@"
!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|scm|el|org|conf|ini|toml|yaml|yml|nix = ${VISUAL:-$EDITOR} -- "$@"

ext x?html?, has chromium, X, flag f = chromium -- "$@"
mime ^image, has chromium, X, flag f = chromium -- "$@"
ext pdf, has chromium, X, flag f = chromium -- "$@"

mime ^ranger/x-terminal-emulator, has kitty = kitty -- "$@"

label editor = ${VISUAL:-$EDITOR} -- "$@"
label pager = ${PAGER:-less} -- "$@"
